# Change these first
owner: lcuellar-tiendapp # Your GitHub organization or username, where this repository lives
repo: tiendapp-status # The name of this repository

sites:
  - name: Página web
    url: https://www.tiendapp.net
  - name: Portal administrador
    url: https://administrador.tiendapp.net
  - name: API Servicios APP
    url: $API_APP
    expectedStatusCodes:
      - 400
  - name: API Conexión ERP
    url: $API_ERP
    expectedStatusCodes:
      - 405
  - name: No conexión
    url: $COUCHDB

status-website:
  favicon: https://administrador.tiendapp.net/favicon.ico
  #themes: ocean, light, dark, night
  theme: night
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.tiendapp.net
  # baseUrl: /tiendapp-status
  logoUrl: https://developer.tiendapp.net/TAPP/images/logo-f1c7a22f.png
  name: Uptime TiendAPP
  introTitle: "**TiendAPP** una tienda a otro nivel"
  introMessage: Uptime sitios web TiendAPP.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
